# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/qti-telephony//setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter arm64,$(TARGET_ARCH)),)

endif
