# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/qti-telephony//setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/qti-telephony/


PRODUCT_PACKAGES += \
    QtiTelephony \
    ims \
    qti-telephony-common
